### ISSUE TITLE
Items from Google Content Items dont get deleted or synchronized?

### ISSUE THREAD

**Issue by jitendrasaini** [bluevisiontec/GoogleShoppingApi#27]
I am trying to delete the product from Google Content Items. When i checked the checkbox of the product and choose 'Delete' from the action drop down and click Submit, then it asked for confirmation and then i got the message 'Google Shopping synchronization process is running'.

After that the page getting reloaded but when i search for that item in Google Content Items, it is still there.

Please advice!

**Comment by jitendrasaini** [comment]
When i checked the exception.log, i noticed the following error - 
exception 'Google_Service_Exception' with message 'Error calling DELETE https://www.googleapis.com/content/v2/XXXXXXX/products/online%3Aen%3AUS%3A1431_1: (404) item not found' in /vendor/google/apiclient/src/Google/Http/REST.php:83

**Comment by schnere** [comment]
The error means that there is no product with the ID 1431_1 on Google Merchants. So, you are trying to remove a product which is already removed?

**Comment by jitendrasaini** [comment]
Ok, but why this product is showing in my magento backend? What should i do, so that i will have the list as on Google Merchants?

**Comment by schnere** [comment]
Mhm, did you migrate from the original Magento GoogleShopping module?
I'll check that in the next days, so that you will be able to delete the product...

**Comment by jitendrasaini** [comment]
Previously i had the Magento's Google Shopping extension. I believe it was http://www.magentocommerce.com/magento-connect/google-content-api-for-shopping.html

**Comment by jonatanaxe** [comment]
I am also from that mistake.
I deleted the product of google shopping and then went delete it appears admin error.

**Comment by schnere** [comment]
Hi, should be fixed in next commit. The module now checks if the item is not listed on GoogleContent and deletes the item from the list, if so.

**Comment by lewisak** [comment]
Hi schnere, I am still experiencing this issue.

Is the fix to delete items not present in Google content something that only occurs during install? Or can I force the already installed module to refresh/delete the list of products that existed in the original API v1 module?

Other than that, the module seems to be working fine. I can load new products to Google, but any products that existed in the original Magento shopping module are stuck, cant delete them.
